### ISSUE TITLE
YAML may be malformed, or contain unexpected information

### ISSUE THREAD

**Issue by ross-spencer** [exponential-decay/demystify#95]
Apparently some files can be packaged with `\0d` characters in the filename. E.g. 

```yaml
---
filename : 'Mac RF Test.zip#Mac RF Test\ProTools AppleSingle\Demo Session\Audio Files\Icon
'
filesize : 0
modified : 1996-11-14T13:29:32Z
errors   : 'empty source'
matches  :
  - ns      : 'pronom'
    id      : 'UNKNOWN'
    format  : 
    version : 
    mime    : 
    basis   : 
    warning : 'no match'
---
filename : 'Mac RF Test.zip#__MACOSX\Mac RF Test\ProTools AppleSingle\Demo Session\Audio Files\._Icon
'
filesize : 2790
modified : 1996-11-14T13:29:32Z
errors   : 
matches  :
  - ns      : 'pronom'
    id      : 'fmt/503'
    format  : 'AppleDouble Resource Fork'
    version : '2'
    mime    : 'multipart/appledouble'
    basis   : 'byte match at 0, 8'
    warning : 
---
filename : 'Mac RF Test.zip#Mac RF Test\ProTools AppleSingle\Demo Session\Audio Files\Icon
.as'
filesize : 2829
modified : 2022-03-03T10:20:10Z
errors   : 
matches  :
  - ns      : 'pronom'
    id      : 'fmt/968'
    format  : 'AppleSingle'
    version : '2'
    mime    : 'application/applefile'
    basis   : 'byte match at 0, 8'
    warning : 
---
```

Visible in the attached ZIP: [Mac RF Test.zip](https://github.com/exponential-decay/demystify/files/9524947/Mac.RF.Test.zip) (from Tyler Thorstead's iPRES sample set)

Demystify won't handle this and so we need to detect the formatting issue and then react to it so that a report can still be generated.
